export const cities = [
  {
    id: 1,
    slug: "berlin",
    name: "Berlin",
    description: "...",
    color: "#FFED62",
  },
  {
    id: 2,
    slug: "new-york",
    name: "New York",
    description: "...",
    color: "#FFCA76",
  },
  {
    id: 3,
    slug: "tokyo",
    name: "Tokyo",
    description: "...",
    color: "#FF9871",
  },
  {
    id: 4,
    slug: "buenos-aires",
    name: "Buenos Aires",
    description: "...",
    color: "#FF8AAB",
  },
  {
    id: 5,
    slug: "sidney",
    name: "Sidney",
    description: "...",
    color: "#D978FF",
  },
  {
    id: 6,
    slug: "paris",
    name: "Paris",
    description: "...",
    color: "#9685FF",
  },
  {
    id: 7,
    slug: "san-francisco",
    name: "San Francisco",
    description: "...",
    color: "#88CCFF",
  },
  { id: 8, slug: "lima", name: "Lima", description: "...", color: "#64DBC7" },
  { id: 9, slug: "seoul", name: "Seoul", description: "...", color: "#7AF093" },
  {
    id: 10,
    slug: "madrid",
    name: "Madrid",
    description: "...",
    color: "#D5FF85",
  },
];
